# nq_backtester.spec
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

a = Analysis(
    ['src/main.py'],
    pathex=['.', 'src'],
    binaries=[],
    datas=collect_data_files('yfinance') + collect_data_files('pyqtgraph'),
    hiddenimports=[
        # PySide6 — 필요한 모듈만 명시 (collect_submodules 사용 금지 → 시작 속도 저하)
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtOpenGL',
        'PySide6.QtOpenGLWidgets',
        'PySide6.QtPrintSupport',
        # pyqtgraph 핵심 모듈
        'pyqtgraph',
        'pyqtgraph.graphicsItems.PlotDataItem',
        'pyqtgraph.graphicsItems.PlotItem',
        'pyqtgraph.graphicsItems.GraphicsObject',
        'pyqtgraph.graphicsItems.ScatterPlotItem',
        'pyqtgraph.graphicsItems.InfiniteLine',
        'pyqtgraph.graphicsItems.TextItem',
        'pyqtgraph.graphicsItems.BarGraphItem',
        'pyqtgraph.graphicsItems.LinearRegionItem',
        'pyqtgraph.graphicsItems.ViewBox',
        'pyqtgraph.widgets.PlotWidget',
        'pyqtgraph.widgets.GraphicsLayoutWidget',
        # 데이터/수치
        'pandas',
        'pandas.core.arrays.masked',
        'pandas.core.arrays.integer',
        'pandas.core.arrays.floating',
        'pandas.io.formats.style',
        'numpy',
        'numpy.core._multiarray_umath',
        # yfinance 의존성
        'yfinance',
        'curl_cffi',
        'curl_cffi.requests',
        'bs4',
        'frozendict',
        'websockets',
        'google.protobuf',
        # 기타
        'sqlite3',
        'pyarrow',
        # 앱 모듈
        'data.fetcher',
        'data.cache',
        'data.store',
        'indicators',
        'engine.base_strategy',
        'engine.strategies',
        'engine.backtest',
        'engine.performance',
        'ui.main_window',
        'ui.chart_widget',
        'ui.settings_panel',
        'ui.performance_panel',
        'ui.trades_table',
        'ui.worker',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # 불필요한 PySide6 모듈 제외 → 번들 크기/로딩 시간 감소
        'PySide6.Qt3DAnimation',
        'PySide6.Qt3DCore',
        'PySide6.Qt3DExtras',
        'PySide6.Qt3DInput',
        'PySide6.Qt3DLogic',
        'PySide6.Qt3DRender',
        'PySide6.QtBluetooth',
        'PySide6.QtCharts',
        'PySide6.QtDataVisualization',
        'PySide6.QtDesigner',
        'PySide6.QtHelp',
        'PySide6.QtLocation',
        'PySide6.QtMultimedia',
        'PySide6.QtMultimediaWidgets',
        'PySide6.QtNfc',
        'PySide6.QtPositioning',
        'PySide6.QtQml',
        'PySide6.QtQuick',
        'PySide6.QtQuickControls2',
        'PySide6.QtQuickWidgets',
        'PySide6.QtRemoteObjects',
        'PySide6.QtScxml',
        'PySide6.QtSensors',
        'PySide6.QtSerialBus',
        'PySide6.QtSerialPort',
        'PySide6.QtSpatialAudio',
        'PySide6.QtSql',
        'PySide6.QtStateMachine',
        'PySide6.QtSvg',
        'PySide6.QtSvgWidgets',
        'PySide6.QtTest',
        'PySide6.QtUiTools',
        'PySide6.QtWebChannel',
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebEngineQuick',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtWebSockets',
        'PySide6.QtXml',
        # 불필요한 기타 모듈
        'tkinter',
        'matplotlib',
        'scipy',
        'IPython',
        'jupyter',
        'notebook',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name='NQBacktester',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,   # UPX 비활성화 — macOS에서 압축 해제 오버헤드 제거
    console=False,
    disable_windowed_traceback=False,
)

coll = COLLECT(
    exe, a.binaries, a.zipfiles, a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='NQBacktester',
)
